### ISSUE TITLE
JOSS Review: minor issues with software installation and documentation

### ISSUE THREAD

**Issue by richings** [silkemaes/MACE#7]
Hi @silkemaes. I am reviewing your MACE software paper for JOSS (the JOSS review thread can be found [here](https://github.com/openjournals/joss-reviews/issues/7148)

I am trying to set up MACE so I can run the software and test the reproducibility of the results. However, I had a few questions about the Documentation and how to install the software: 

- Is there an automated way to install all of the dependencies/pre-requisites? I was finding I had to pip install all the pre-requisites (e.g. torch) manually, but I wasn't sure if there was a list somewhere with all of the dependencies (sorry if I've missed this!). I think I saw that Steven Rieder has an open pull request to add a "requirements.txt" file, which I think should solve this. 

- In the README you have a few paragraphs on How to Run, but I wasn't sure exactly how to do this. For example, it says about setting up the Dataset class, and it points to the dataset.py file, but I wasn't sure how to set up the Dataset class. I tried to just run the run.py script, but it gives a File Not Found error as it couldn't load the file MACE/data/rate16.specs. Do I need to download this file? Sorry, I couldn't find it on the repository. 

- It looks like there is a Sphinx "Read the Docs" documentation (e.g. I can see a readthedocs.yaml file), but I wasn't sure where to find the documentation itself? Do I need to "compile/build" this documentation as it were? (Sorry if I've missed it!). 

- I saw there were a few Jupter Notebooks in the repository as well, are these designed to be introductory tutorials for new users to help learn how to use the code? I tried running the robustness.ipynb notebook, but I encountered the same error with the rate16.specs file not found.

**Comment by silkemaes** [comment]
Hi @richings.

First of all thank you for reviewing, and sorry for the late response. First of all, I don't know if it was clear, but the aim was for the JOSS reviewers to review the code in the branch JOSS.

- There is no automated way to install MACE currently, it is best to just clone the repo. I added this in the readme file, and merged the pull request of Steven Rieder for the ```requirements.txt```.
- You are right that is was not very clear how to run MACE. I now adjusted the explanation in the readme. I renamed the ```run.py``` file to ```routine.py``` in order to mitigate some confusion. Namely, MACE cannot just be 'ran', it can only be trained. The routine to train MACE is the current ```routine.py``` file. About the ```Dataset``` class, when training an architecture with PyTorch, the data needs to be in the correct tensor form. The script ```dataset.py``` makes sure that my data is converted in the correct way for PyTorch to use it for training. However, this script is only applicable for my specific case. If someone wants to train a MACE architecture themselves, they first need to rewrite the ```dataset.py``` script. Hence, It is better to test a trained MACE model using the notebook in the [Documentation](https://mace-code.readthedocs.io/en/latest/use/index.html).
- The documentation is available online: https://mace-code.readthedocs.io/.
- The notebook on robustness does not need to be reviewed, since this was not originally submitted to JOSS.

**Comment by richings** [comment]
Hi @silkemaes 

Many thanks for your response! Sorry, you're right, I was looking at the wrong branch! I'll switch to the JOSS branch for the review. 

The updates to the README are much clearer, thanks for the clarifications! There was just one minor thing - in the "How to use?" section you include a link to an annotated notebook to show how to use the routine for training the MACE model. However, I think this link is broken, it gives me a 404 error? I was able to find the notebook on the mace-code.readthedocs.io web page though, I think it's just an incorrect url in the README. 

The link to the other annotated notebook, in the "Example case" section of the README, does work fine though.

**Comment by silkemaes** [comment]
Hi @richings,

You are right! With changing a bit the documentation, the link changed. I fixed this now.

**Comment by richings** [comment]
Hi @silkemaes 

Great, thanks! That's fixed the link on the JOSS branch, although I think the link is still broken on the Readme on the main branch of the repository?

**Comment by silkemaes** [comment]
Hi @richings, yes you are right, I still need to push the readme with the updated links to the main branch.

**Comment by silkemaes** [comment]
I have updated the readme on the main branch.

**Comment by richings** [comment]
Great, thanks! That all looks good!
